use once_cell::sync::Lazy;

use crate::core::domain::{SkillPack, ToolManifest, ToolRiskLevel};

pub static BUILTIN_TOOLS: Lazy<Vec<ToolManifest>> = Lazy::new(|| {
    vec![
        ToolManifest {
            id: "Task".into(),
            name: "Task".into(),
            category: "coordination".into(),
            risk_level: ToolRiskLevel::Medium,
            input_schema: r#"{"type":"object","properties":{"description":{"type":"string"},"prompt":{"type":"string"},"subagent_type":{"type":"string"}},"required":["description","prompt","subagent_type"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"status":"string","task":"object"}"#.into(),
            timeout_ms: 30_000,
            concurrency_limit: 2,
            permissions: vec!["coordination:task".into()],
            description: "Launch a specialized subagent for complex, multi-step work. Must specify a subagent_type (Explore, Plan, general-purpose, etc.). Do NOT use for simple file reads or single tool calls — invoke those tools directly instead.".into(),
        },
        ToolManifest {
            id: "AskUserQuestion".into(),
            name: "AskUserQuestion".into(),
            category: "coordination".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"question":{"type":"string"},"options":{"type":"array","items":{"type":"string"}},"context":{"type":"string"},"allow_free_form":{"type":"boolean"}},"required":["question"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"status":"string","question":"string","options":"array?","allowFreeForm":"boolean"}"#.into(),
            timeout_ms: 5_000,
            concurrency_limit: 1,
            permissions: vec!["coordination:user_input".into()],
            description: "Ask the user one clarifying question and pause until they reply. Use only when requirements are genuinely ambiguous and cannot be inferred. Avoid asking unnecessary or redundant questions.".into(),
        },
        ToolManifest {
            id: "TaskCreate".into(),
            name: "TaskCreate".into(),
            category: "coordination".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"subject":{"type":"string"},"description":{"type":"string"},"activeForm":{"type":"string"}},"required":["subject","description"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"id":"string","subject":"string","description":"string","status":"string"}"#.into(),
            timeout_ms: 5_000,
            concurrency_limit: 6,
            permissions: vec!["coordination:summary".into()],
            description: "Create a new task with a subject and description. Returns the task id. Use to track multi-step work — create one task per logical unit before starting execution. Call TaskList to see existing tasks before creating duplicates.".into(),
        },
        ToolManifest {
            id: "TaskGet".into(),
            name: "TaskGet".into(),
            category: "coordination".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"taskId":{"type":"string"}},"required":["taskId"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"id":"string","subject":"string","description":"string","activeForm":"string?","status":"string","owner":"string?","blocks":["string"],"blockedBy":["string"]}"#.into(),
            timeout_ms: 5_000,
            concurrency_limit: 6,
            permissions: vec!["coordination:summary".into()],
            description: "Retrieve full details of a task by its id, including status, description, and dependency relationships.".into(),
        },
        ToolManifest {
            id: "TaskUpdate".into(),
            name: "TaskUpdate".into(),
            category: "coordination".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"taskId":{"type":"string"},"subject":{"type":"string"},"description":{"type":"string"},"activeForm":{"type":"string"},"status":{"type":"string","enum":["pending","in_progress","completed","deleted"]},"addBlocks":{"type":"array","items":{"type":"string"}},"addBlockedBy":{"type":"array","items":{"type":"string"}},"owner":{"type":"string"}},"required":["taskId"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"id":"string","subject":"string","status":"string","owner":"string?","blocks":["string"],"blockedBy":["string"]}"#.into(),
            timeout_ms: 5_000,
            concurrency_limit: 6,
            permissions: vec!["coordination:summary".into()],
            description: "Update task fields: status (pending/in_progress/completed/deleted), subject, description, owner, or append dependency ids via addBlocks/addBlockedBy. Mark exactly one task in_progress at a time. Update status after every state change.".into(),
        },
        ToolManifest {
            id: "TaskList".into(),
            name: "TaskList".into(),
            category: "coordination".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{},"additionalProperties":false}"#.into(),
            output_schema: r#"{"tasks":[{"id":"string","subject":"string","status":"string","owner":"string?","blockedBy":["string"]}]}"#.into(),
            timeout_ms: 5_000,
            concurrency_limit: 6,
            permissions: vec!["coordination:summary".into()],
            description: "List all non-deleted tasks for the current session, showing id, subject, status, owner, and blockedBy. Call before creating tasks to avoid duplicates, and periodically to track overall progress.".into(),
        },
        ToolManifest {
            id: "Bash".into(),
            name: "Bash".into(),
            category: "system".into(),
            risk_level: ToolRiskLevel::High,
            input_schema: r#"{"type":"object","properties":{"command":{"type":"string"},"timeout":{"type":"number"},"description":{"type":"string"},"run_in_background":{"type":"boolean"},"dangerouslyDisableSandbox":{"type":"boolean"}},"required":["command"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"bash_id":"string?","stdout":"string","stderr":"string","status":"number"}"#.into(),
            timeout_ms: 120_000,
            concurrency_limit: 2,
            permissions: vec!["system:shell".into()],
            description: "Execute shell commands (git, npm, docker, compilers, etc.) with optional background mode. Do NOT use for file operations — use Read, Write, Edit, Glob, or Grep instead. Never invoke find, grep, cat, head, tail, sed, or awk in Bash; use the dedicated tools instead.".into(),
        },
        ToolManifest {
            id: "Glob".into(),
            name: "Glob".into(),
            category: "workspace".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"pattern":{"type":"string"},"path":{"type":"string"}},"required":["pattern"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"matches":["string"]}"#.into(),
            timeout_ms: 15_000,
            concurrency_limit: 4,
            permissions: vec!["workspace:index".into()],
            description: "Find files by name pattern using glob syntax (e.g. **/*.ts, src/**/*.rs). Returns paths sorted by modification time. Prefer this over Bash find for all file discovery tasks. Multiple globs can run in parallel.".into(),
        },
        ToolManifest {
            id: "Grep".into(),
            name: "Grep".into(),
            category: "workspace".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"pattern":{"type":"string"},"path":{"type":"string"},"glob":{"type":"string"},"output_mode":{"type":"string","enum":["content","files_with_matches","count"]},"-A":{"type":"number"},"-B":{"type":"number"},"-C":{"type":"number"},"-n":{"type":"boolean"},"-i":{"type":"boolean"},"type":{"type":"string"},"head_limit":{"type":"number"},"multiline":{"type":"boolean"}},"required":["pattern"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"matches":["string"],"count":"number?"}"#.into(),
            timeout_ms: 20_000,
            concurrency_limit: 3,
            permissions: vec!["workspace:index".into()],
            description: "Search file contents with regex (ripgrep). Use output_mode: \"content\" for matching lines with context, \"files_with_matches\" for paths only. Filter by glob or type parameter. Never run grep or rg in Bash — always use this tool instead.".into(),
        },
        ToolManifest {
            id: "Skill".into(),
            name: "Skill".into(),
            category: "workspace".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"skill":{"type":"string","description":"The skill name. E.g., \"commit\", \"review-pr\", or \"pdf\""},"args":{"type":"string","description":"Optional arguments for the skill"}},"required":["skill"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"action":"string","skills":"array?","skill":"object?","content":"string?","path":"string?","filePath":"string?","runtimeHint":"string?"}"#.into(),
            timeout_ms: 15_000,
            concurrency_limit: 4,
            permissions: vec!["workspace:index".into()],
            description: "Execute a skill within the main conversation. When users ask you to perform tasks, check if any of the available skills match — skills are listed in the enabled skills catalog. When a skill matches the request, invoking this tool is a BLOCKING REQUIREMENT: call it BEFORE generating any other response about the task. When users run a slash command or reference /<something>, they are referring to a skill. Do not invoke a skill that is already running. Do not guess skill names — only use skills listed in the catalog.".into(),
        },
        ToolManifest {
            id: "LS".into(),
            name: "LS".into(),
            category: "filesystem".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"path":{"type":"string"},"ignore":{"type":"array","items":{"type":"string"}}},"required":["path"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"entries":["string"]}"#.into(),
            timeout_ms: 10_000,
            concurrency_limit: 6,
            permissions: vec!["fs:read".into()],
            description: "List files and directories at an absolute path with optional ignore patterns. Use Glob for pattern-based file discovery; use LS for simple directory inspection.".into(),
        },
        ToolManifest {
            id: "Read".into(),
            name: "Read".into(),
            category: "filesystem".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"file_path":{"type":"string"},"offset":{"type":"number"},"limit":{"type":"number"}},"required":["file_path"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"content":"string","file_path":"string"}"#.into(),
            timeout_ms: 20_000,
            concurrency_limit: 4,
            permissions: vec!["fs:read".into()],
            description: "Read file contents with optional line offset and limit. Always read a file before editing it. For large files, use offset and limit to read specific sections. Do NOT use Bash cat or head — always use this tool for reading files.".into(),
        },
        ToolManifest {
            id: "Edit".into(),
            name: "Edit".into(),
            category: "filesystem".into(),
            risk_level: ToolRiskLevel::High,
            input_schema: r#"{"type":"object","properties":{"file_path":{"type":"string"},"old_string":{"type":"string"},"new_string":{"type":"string"},"replace_all":{"type":"boolean"}},"required":["file_path","old_string","new_string"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"status":"string","replacements":"number","file_path":"string"}"#.into(),
            timeout_ms: 20_000,
            concurrency_limit: 2,
            permissions: vec!["fs:read".into(), "fs:write".into()],
            description: "Performs exact string replacements in files.\n\nUsage:\n- You must use your `Read` tool at least once in the conversation before editing. This tool will error if you attempt an edit without reading the file. \n- When editing text from Read tool output, ensure you preserve the exact indentation (tabs/spaces) as it appears AFTER the line number prefix. The line number prefix format is: spaces + line number + tab. Everything after that tab is the actual file content to match. Never include any part of the line number prefix in the old_string or new_string.\n- ALWAYS prefer editing existing files in the codebase. NEVER write new files unless explicitly required.\n- Only use emojis if the user explicitly requests it. Avoid adding emojis to files unless asked.\n- The edit will FAIL if `old_string` is not unique in the file. Either provide a larger string with more surrounding context to make it unique or use `replace_all` to change every instance of `old_string`.\n- Use `replace_all` for replacing and renaming strings across the file. This parameter is useful if you want to rename a variable for instance.".into(),
        },
        ToolManifest {
            id: "Write".into(),
            name: "Write".into(),
            category: "filesystem".into(),
            risk_level: ToolRiskLevel::High,
            input_schema: r#"{"type":"object","properties":{"file_path":{"type":"string"},"content":{"type":"string"}},"required":["file_path","content"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"status":"string","file_path":"string"}"#.into(),
            timeout_ms: 20_000,
            concurrency_limit: 2,
            permissions: vec!["fs:write".into()],
            description: "Write or overwrite full file contents. Must read the file first if it already exists. Prefer Edit for targeted changes; use Write only when replacing the entire file or creating a new file.".into(),
        },
        ToolManifest {
            id: "WebFetch".into(),
            name: "WebFetch".into(),
            category: "network".into(),
            risk_level: ToolRiskLevel::Medium,
            input_schema: r#"{"type":"object","properties":{"url":{"type":"string","format":"uri"},"prompt":{"type":"string"}},"required":["url","prompt"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"url":"string","status":"number","analysis":"string"}"#.into(),
            timeout_ms: 20_000,
            concurrency_limit: 3,
            permissions: vec!["network:http".into()],
            description: "Fetch a URL and return a prompt-focused analysis of the page content. HTTP is automatically upgraded to HTTPS. Use for reading documentation, specs, or linked resources. For general search use WebSearch instead.".into(),
        },

        ToolManifest {
            id: "WebSearch".into(),
            name: "WebSearch".into(),
            category: "network".into(),
            risk_level: ToolRiskLevel::Medium,
            input_schema: r#"{"type":"object","properties":{"query":{"type":"string","minLength":2},"allowed_domains":{"type":"array","items":{"type":"string"}},"blocked_domains":{"type":"array","items":{"type":"string"}}},"required":["query"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"query":"string","results":"array"}"#.into(),
            timeout_ms: 20_000,
            concurrency_limit: 3,
            permissions: vec!["network:http".into()],
            description: "Run a web search and return summarized result snippets with sources. Use for current events, up-to-date documentation, or facts beyond training cutoff. Always include a Sources section in your response with the result URLs.".into(),
        },
        ToolManifest {
            id: "RequestPeerInput".into(),
            name: "RequestPeerInput".into(),
            category: "coordination".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"targetAgentId":{"type":"string","description":"The ID of the peer agent to request input from"},"question":{"type":"string","description":"The question or sub-task for the peer agent"},"context":{"type":"string","description":"Optional additional context"}},"required":["targetAgentId","question"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"answer":"string","peerAgentId":"string"}"#.into(),
            timeout_ms: 300_000,
            concurrency_limit: 2,
            permissions: vec!["coordination:peer_input".into()],
            description: "Request input or expert analysis from a specific peer agent in the same work group. The calling task will be paused until the peer agent completes the sub-task and returns a result. Use when you need another agent's specialized knowledge or when a task depends on another agent's output.".into(),
        },
        ToolManifest {
            id: "TaskOutput".into(),
            name: "TaskOutput".into(),
            category: "system".into(),
            risk_level: ToolRiskLevel::Medium,
            input_schema: r#"{"type":"object","properties":{"task_id":{"type":"string"},"block":{"type":"boolean"},"timeout":{"type":"number","minimum":0,"maximum":600000}},"required":["task_id"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"task_id":"string","status":"string","stdout":"string","stderr":"string"}"#.into(),
            timeout_ms: 30_000,
            concurrency_limit: 4,
            permissions: vec!["system:shell".into()],
            description: "Retrieve output from a running or completed background task (shell or agent) by task_id. Use after launching a command with run_in_background=true. Set block=true (default) to wait for completion, block=false for a non-blocking status check.".into(),
        },
        ToolManifest {
            id: "TaskStop".into(),
            name: "TaskStop".into(),
            category: "system".into(),
            risk_level: ToolRiskLevel::High,
            input_schema: r#"{"type":"object","properties":{"task_id":{"type":"string"},"shell_id":{"type":"string","description":"Deprecated: use task_id instead"}},"additionalProperties":false}"#.into(),
            output_schema: r#"{"task_id":"string","killed":"boolean"}"#.into(),
            timeout_ms: 10_000,
            concurrency_limit: 2,
            permissions: vec!["system:shell".into()],
            description: "Terminate a running background task by task_id. Use when a background process is no longer needed, is hanging, or must be stopped before starting a new one.".into(),
        },
    ]
});

pub static BUILTIN_SKILLS: Lazy<Vec<SkillPack>> = Lazy::new(|| {
    vec![
        SkillPack {
            id: "skill.research".into(),
            name: "Research Sweep".into(),
            prompt_template: "Break the task into evidence collection, synthesis, and gaps.".into(),
            planning_rules: vec![
                "Collect facts before proposing action.".into(),
                "Surface uncertainty explicitly.".into(),
            ],
            allowed_tool_tags: vec!["workspace".into(), "network".into(), "coordination".into()],
            done_criteria: vec!["Summarize findings".into(), "Call out blockers".into()],
            enabled: true,
            editable: false,
            source: "builtin".into(),
            install_path: None,
        },
        SkillPack {
            id: "skill.builder".into(),
            name: "Builder Loop".into(),
            prompt_template: "Prefer implementation-ready artifacts and concrete next steps."
                .into(),
            planning_rules: vec![
                "Decompose by dependency order.".into(),
                "Prefer actionable outputs.".into(),
            ],
            allowed_tool_tags: vec![
                "filesystem".into(),
                "workspace".into(),
                "system".into(),
                "coordination".into(),
            ],
            done_criteria: vec![
                "Produce runnable changes".into(),
                "Explain verification".into(),
            ],
            enabled: true,
            editable: false,
            source: "builtin".into(),
            install_path: None,
        },
        SkillPack {
            id: "skill.reviewer".into(),
            name: "Reviewer Lens".into(),
            prompt_template: "Prioritize correctness risks, regressions, and missing coverage."
                .into(),
            planning_rules: vec![
                "Look for edge cases and broken invariants.".into(),
                "Prefer concrete evidence over vague concern.".into(),
            ],
            allowed_tool_tags: vec![
                "workspace".into(),
                "filesystem".into(),
                "coordination".into(),
            ],
            done_criteria: vec![
                "List material findings".into(),
                "State residual risks".into(),
            ],
            enabled: true,
            editable: false,
            source: "builtin".into(),
            install_path: None,
        },
    ]
});
