use once_cell::sync::Lazy;

use crate::core::domain::{SkillPack, ToolManifest, ToolRiskLevel};

pub static BUILTIN_TOOLS: Lazy<Vec<ToolManifest>> = Lazy::new(|| {
    vec![
        ToolManifest {
            id: "Task".into(),
            name: "Task".into(),
            category: "coordination".into(),
            risk_level: ToolRiskLevel::Medium,
            input_schema: r#"{"type":"object","properties":{"description":{"type":"string"},"prompt":{"type":"string"},"subagent_type":{"type":"string"}},"required":["description","prompt","subagent_type"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"status":"string","task":"object"}"#.into(),
            timeout_ms: 30_000,
            concurrency_limit: 2,
            permissions: vec!["coordination:task".into()],
            description: "Launch a sub-task request for specialized handling.".into(),
        },
        ToolManifest {
            id: "Bash".into(),
            name: "Bash".into(),
            category: "system".into(),
            risk_level: ToolRiskLevel::High,
            input_schema: r#"{"type":"object","properties":{"command":{"type":"string"},"timeout":{"type":"number"},"description":{"type":"string"},"run_in_background":{"type":"boolean"}},"required":["command"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"bash_id":"string?","stdout":"string","stderr":"string","status":"number"}"#.into(),
            timeout_ms: 120_000,
            concurrency_limit: 2,
            permissions: vec!["system:shell".into()],
            description: "Execute shell command with optional background mode.".into(),
        },
        ToolManifest {
            id: "Glob".into(),
            name: "Glob".into(),
            category: "workspace".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"pattern":{"type":"string"},"path":{"type":"string"}},"required":["pattern"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"matches":["string"]}"#.into(),
            timeout_ms: 15_000,
            concurrency_limit: 4,
            permissions: vec!["workspace:index".into()],
            description: "Fast file path matching using glob patterns.".into(),
        },
        ToolManifest {
            id: "Grep".into(),
            name: "Grep".into(),
            category: "workspace".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"pattern":{"type":"string"},"path":{"type":"string"},"glob":{"type":"string"},"output_mode":{"type":"string","enum":["content","files_with_matches","count"]},"-A":{"type":"number"},"-B":{"type":"number"},"-C":{"type":"number"},"-n":{"type":"boolean"},"-i":{"type":"boolean"},"type":{"type":"string"},"head_limit":{"type":"number"},"multiline":{"type":"boolean"}},"required":["pattern"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"matches":["string"],"count":"number?"}"#.into(),
            timeout_ms: 20_000,
            concurrency_limit: 3,
            permissions: vec!["workspace:index".into()],
            description: "Search file contents with regex and output modes.".into(),
        },
        ToolManifest {
            id: "LS".into(),
            name: "LS".into(),
            category: "filesystem".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"path":{"type":"string"},"ignore":{"type":"array","items":{"type":"string"}}},"required":["path"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"entries":["string"]}"#.into(),
            timeout_ms: 10_000,
            concurrency_limit: 6,
            permissions: vec!["fs:read".into()],
            description: "List files and directories in an absolute path.".into(),
        },
        ToolManifest {
            id: "ExitPlanMode".into(),
            name: "ExitPlanMode".into(),
            category: "coordination".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"plan":{"type":"string"}},"required":["plan"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"status":"string","plan":"string"}"#.into(),
            timeout_ms: 5_000,
            concurrency_limit: 8,
            permissions: vec!["coordination:summary".into()],
            description: "Record the final implementation plan before coding.".into(),
        },
        ToolManifest {
            id: "Read".into(),
            name: "Read".into(),
            category: "filesystem".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"file_path":{"type":"string"},"offset":{"type":"number"},"limit":{"type":"number"}},"required":["file_path"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"content":"string","file_path":"string"}"#.into(),
            timeout_ms: 20_000,
            concurrency_limit: 4,
            permissions: vec!["fs:read".into()],
            description: "Read file content with optional line window.".into(),
        },
        ToolManifest {
            id: "Edit".into(),
            name: "Edit".into(),
            category: "filesystem".into(),
            risk_level: ToolRiskLevel::High,
            input_schema: r#"{"type":"object","properties":{"file_path":{"type":"string"},"old_string":{"type":"string"},"new_string":{"type":"string"},"replace_all":{"type":"boolean"}},"required":["file_path","old_string","new_string"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"status":"string","replacements":"number","file_path":"string"}"#.into(),
            timeout_ms: 20_000,
            concurrency_limit: 2,
            permissions: vec!["fs:read".into(), "fs:write".into()],
            description: "Replace exact text in a file.".into(),
        },
        ToolManifest {
            id: "MultiEdit".into(),
            name: "MultiEdit".into(),
            category: "filesystem".into(),
            risk_level: ToolRiskLevel::High,
            input_schema: r#"{"type":"object","properties":{"file_path":{"type":"string"},"edits":{"type":"array","items":{"type":"object","properties":{"old_string":{"type":"string"},"new_string":{"type":"string"},"replace_all":{"type":"boolean"}},"required":["old_string","new_string"],"additionalProperties":false},"minItems":1}},"required":["file_path","edits"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"status":"string","replacements":"number","file_path":"string"}"#.into(),
            timeout_ms: 25_000,
            concurrency_limit: 2,
            permissions: vec!["fs:read".into(), "fs:write".into()],
            description: "Apply multiple sequential edits atomically.".into(),
        },
        ToolManifest {
            id: "Write".into(),
            name: "Write".into(),
            category: "filesystem".into(),
            risk_level: ToolRiskLevel::High,
            input_schema: r#"{"type":"object","properties":{"file_path":{"type":"string"},"content":{"type":"string"}},"required":["file_path","content"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"status":"string","file_path":"string"}"#.into(),
            timeout_ms: 20_000,
            concurrency_limit: 2,
            permissions: vec!["fs:write".into()],
            description: "Write full file contents.".into(),
        },
        ToolManifest {
            id: "NotebookEdit".into(),
            name: "NotebookEdit".into(),
            category: "filesystem".into(),
            risk_level: ToolRiskLevel::High,
            input_schema: r#"{"type":"object","properties":{"notebook_path":{"type":"string"},"cell_id":{"type":"string"},"new_source":{"type":"string"},"cell_type":{"type":"string","enum":["code","markdown"]},"edit_mode":{"type":"string","enum":["replace","insert","delete"]}},"required":["notebook_path","new_source"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"status":"string","notebook_path":"string"}"#.into(),
            timeout_ms: 25_000,
            concurrency_limit: 1,
            permissions: vec!["fs:read".into(), "fs:write".into()],
            description: "Edit Jupyter notebook cells by ID.".into(),
        },
        ToolManifest {
            id: "WebFetch".into(),
            name: "WebFetch".into(),
            category: "network".into(),
            risk_level: ToolRiskLevel::Medium,
            input_schema: r#"{"type":"object","properties":{"url":{"type":"string","format":"uri"},"prompt":{"type":"string"}},"required":["url","prompt"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"url":"string","status":"number","analysis":"string"}"#.into(),
            timeout_ms: 20_000,
            concurrency_limit: 3,
            permissions: vec!["network:http".into()],
            description: "Fetch a webpage and return prompt-focused analysis.".into(),
        },
        ToolManifest {
            id: "TodoWrite".into(),
            name: "TodoWrite".into(),
            category: "coordination".into(),
            risk_level: ToolRiskLevel::Low,
            input_schema: r#"{"type":"object","properties":{"todos":{"type":"array","items":{"type":"object","properties":{"content":{"type":"string"},"status":{"type":"string","enum":["pending","in_progress","completed"]},"id":{"type":"string"}},"required":["content","status","id"],"additionalProperties":false}}},"required":["todos"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"status":"string","count":"number","todos":"array"}"#.into(),
            timeout_ms: 5_000,
            concurrency_limit: 6,
            permissions: vec!["coordination:summary".into()],
            description: "Update structured todo list state for current run.".into(),
        },
        ToolManifest {
            id: "WebSearch".into(),
            name: "WebSearch".into(),
            category: "network".into(),
            risk_level: ToolRiskLevel::Medium,
            input_schema: r#"{"type":"object","properties":{"query":{"type":"string","minLength":2},"allowed_domains":{"type":"array","items":{"type":"string"}},"blocked_domains":{"type":"array","items":{"type":"string"}}},"required":["query"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"query":"string","results":"array"}"#.into(),
            timeout_ms: 20_000,
            concurrency_limit: 3,
            permissions: vec!["network:http".into()],
            description: "Run web search and return summarized result snippets.".into(),
        },
        ToolManifest {
            id: "BashOutput".into(),
            name: "BashOutput".into(),
            category: "system".into(),
            risk_level: ToolRiskLevel::Medium,
            input_schema: r#"{"type":"object","properties":{"bash_id":{"type":"string"},"filter":{"type":"string"}},"required":["bash_id"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"bash_id":"string","status":"string","stdout":"string","stderr":"string"}"#.into(),
            timeout_ms: 10_000,
            concurrency_limit: 4,
            permissions: vec!["system:shell".into()],
            description: "Read incremental output from background bash runs.".into(),
        },
        ToolManifest {
            id: "KillBash".into(),
            name: "KillBash".into(),
            category: "system".into(),
            risk_level: ToolRiskLevel::High,
            input_schema: r#"{"type":"object","properties":{"shell_id":{"type":"string"}},"required":["shell_id"],"additionalProperties":false}"#.into(),
            output_schema: r#"{"shell_id":"string","killed":"boolean"}"#.into(),
            timeout_ms: 10_000,
            concurrency_limit: 2,
            permissions: vec!["system:shell".into()],
            description: "Terminate a background bash shell by ID.".into(),
        },
    ]
});

pub static BUILTIN_SKILLS: Lazy<Vec<SkillPack>> = Lazy::new(|| {
    vec![
        SkillPack {
            id: "skill.research".into(),
            name: "Research Sweep".into(),
            prompt_template: "Break the task into evidence collection, synthesis, and gaps.".into(),
            planning_rules: vec![
                "Collect facts before proposing action.".into(),
                "Surface uncertainty explicitly.".into(),
            ],
            allowed_tool_tags: vec!["workspace".into(), "network".into(), "coordination".into()],
            done_criteria: vec!["Summarize findings".into(), "Call out blockers".into()],
            enabled: true,
            editable: false,
            source: "builtin".into(),
            install_path: None,
        },
        SkillPack {
            id: "skill.builder".into(),
            name: "Builder Loop".into(),
            prompt_template: "Prefer implementation-ready artifacts and concrete next steps."
                .into(),
            planning_rules: vec![
                "Decompose by dependency order.".into(),
                "Prefer actionable outputs.".into(),
            ],
            allowed_tool_tags: vec![
                "filesystem".into(),
                "workspace".into(),
                "coordination".into(),
            ],
            done_criteria: vec!["Produce a change set".into(), "Note verification".into()],
            enabled: true,
            editable: false,
            source: "builtin".into(),
            install_path: None,
        },
        SkillPack {
            id: "skill.reviewer".into(),
            name: "Review Lens".into(),
            prompt_template: "Prioritize regressions, security, and missing tests.".into(),
            planning_rules: vec![
                "List findings by severity.".into(),
                "Separate findings from summary.".into(),
            ],
            allowed_tool_tags: vec!["workspace".into(), "coordination".into()],
            done_criteria: vec!["Identify risks".into(), "Recommend fixes".into()],
            enabled: true,
            editable: false,
            source: "builtin".into(),
            install_path: None,
        },
    ]
});
